"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#1d2230)\
$cmd_duration\
[](fg:#1d2230)\
$character"""

[directory]
style = "fg:#090c0c bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[cmd_duration]
min_time = 2000
style = "bg:#1d2230"
format = '[[ 󱦟 $duration ](fg:#a0a9cb bg:#1d2230)]($style)'

[character]
success_symbol = '[\$](bold #7aa2f7)'
error_symbol = '[\$](bold red)'
