[settings]
minimum_release_age = "2d"
experimental = true

[tools]
# --- Version Control & Git Tools ---
jj = "latest"
jjui = "latest"
lazygit = "latest"
gitu = "latest"
delta = "latest"

# --- Search & Find ---
fd = "latest"
rg = "latest"
fzf = "latest"

# --- Navigation & File Management ---
zoxide = "latest"
yazi = "latest"
vivid = "latest"

# --- Terminal & Shell ---
zellij = "latest"
starship = "latest"

# --- Editor ---
neovim = "latest"
tree-sitter = "latest"
helix = "latest"
"npm:markserv" = "latest"

# --- AI & Assistants ---
opencode = "latest"
difftastic = "latest"
github-cli = "latest"

# --- Languages & Runtimes ---
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
lua-language-server = "latest"
stylua = "latest"
oxfmt = "latest"
qsv = "latest"

[dotfiles]
"~/.zshrc"                    = { source = "../zsh/.zshrc" }
"~/.zshenv"                   = { source = "../zsh/.zshenv" }
"~/.config/starship.toml"     = { source = "../starship.toml" }
"~/.config/ghostty"           = { source = "../ghostty" }
"~/.config/helix"             = { source = "../helix" }
"~/.config/lazygit"           = { source = "../lazygit" }
"~/.config/wezterm"           = { source = "../wezterm" }
"~/.config/nvim"              = { source = "../nvim" }
"~/.config/zellij/config.kdl" = { source = "../zellij/config.kdl" }
"~/.config/mise/config.toml"  = { source = "config.toml" }
