[settings]
minimum_release_age = "2d"

[tools]
# --- Version Control & Git Tools ---
jj = "latest"
jjui = "latest"
lazygit = "latest"
gitu = "latest"
delta = "latest"

# --- Search & Find ---
fd = "latest"
rg = "latest"
fzf = "latest"

# --- Navigation & File Management ---
zoxide = "latest"
yazi = "latest"
vivid = "latest"

# --- Terminal & Shell ---
zellij = "latest"
starship = "latest"

# --- Editor ---
neovim = "latest"
tree-sitter = "latest"
helix = "latest"
"npm:markserv" = "latest"

# --- AI & Assistants ---
opencode = "latest"
difftastic = "latest"
github-cli = "latest"

# --- Languages & Runtimes ---
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
lua-language-server = "latest"
stylua = "latest"
oxfmt = "latest"
qsv = "latest"
