git:
  diffRenderers:
    - command: delta --dark --paging=never --side-by-side
    - command: delta --dark --paging=never
    - type: extDiff
      command: difft --color=always --context={{diffContext}}
    - type: extDiff
      command: difft --display=inline --color=always --context={{diffContext}}
    - type: rawGit # git's default diff
      name: default
gui:
  scrollHeight: 5
  # Fancy icons for the file-tree
  nerdFontsVersion: 3
  # Toggle with '`' if needed, easier disabled for diff reviews
  showFileTree: false
  # More space to the diffs
  sidePanelWidth: 0.2
  # Show the stats in the view
  showNumstatInFilesView: true
  # Match the git default of 7
  commitHashLength: 7
  # Use "standard" of 2
  tabWidth: 2
  # Use 24 hour time
  shortTimeFormat: 15:04:05

worktree:
  defaultPath: ".worktrees"
