git:
  diffRenderers:
    - type: extDiff
      command: difft --color=always --context={{diffContext}}
    - type: extDiff
      command: difft --display=inline --color=always --context={{diffContext}}
    - command: delta --dark --paging=never --side-by-side
    - command: delta --dark --paging=never
    - type: rawGit # git's default diff
      name: default
gui:
  scrollHeight: 5
  # Fancy icons for the file-tree
  nerdFontsVersion: 3
  # Toggle with '`' if needed, easier disabled for diff reviews
  showFileTree: false
  # More space to the diffs
  sidePanelWidth: 0.25

worktree:
  defaultPath: ".worktrees"
