#!/bin/bash

i3status | (read line && echo $line && while :
do
    read line
    net=$(zsh ~/git/utils/netspeed /tmp/i3netspeed)
    line=$(echo $line | sed -e 's/time",/&"color": "#ff9900",/' -e 's/No battery//')
    np="$(sh ~/bin/np.sh)"
    np="{\"full_text\": \"$np\", \"color\": \"#99ff00\"}"
    data="[$np,{\"full_text\": \"$net\", \"color\": \"#ff9977\"},"
    echo "${line/[/$data}" || exit 1
done)
