# Set proper color based if root
[ $UID -eq 0 ] && NCOLOR="red" || NCOLOR="green"

clean_desktop() {
    files=($HOME/*)
    [ ${#files} -gt 50 ] && echo -ne " %{\e[31m\e[1m\e[5m%}*%{$reset_color%}"
}

PROMPT='%{$reset_color%}[%{$fg[$NCOLOR]%}%~$(git_prompt_info)$(clean_desktop)%{$reset_color%}] '

if [[ -o interactive ]]; then
    fakepacdb="/tmp/.localsync/"
    [ -f "${fakepacdb}/updates" ] && cat ${fakepacdb}/updates
fi

# vim: set ft=zsh:
