#! /bin/sh

# shellcheck disable=SC1091
. bspwm_theme

num_mon=$(bspc query -M | wc -l)
sep=' | '

while read -r line ; do
    case $line in
        T*)
            title="${line#?}"
            ;;
        O*)
            offset="%{${line}}"
            ;;
        S*)
            ll=${line#?}
            case $ll in
                B*)
                    battery="${ll#?}"
                    ;;
                D*)
                    date="%{B#504945} ${ll#?} %{B-}"
                    ;;
                T*)
                    dtime="%{B#665c54} ${ll#?} %{B-}"
                    ;;
                L*)
                    load="%{F#d79921}\uf0ae ${ll#?}%{F-}"
                    ;;
                M*)
                    music="%{F#fe8019}${ll#?}%{F-}"
                    ;;
                V*)
                    volume="%{A1:ponymix toggle: A4:ponymix increase 3: A5:ponymix decrease 3:}${ll#?}%{A A A}"
                    ;;
                U*)
                    [ -n "${ll#?}" ] && updates="%{F#8ec07c}\uf103 ${ll#?}%{F-}" || updates=""
                    ;;
            esac
            sys=""
            sys="${sys}${volume}${sep}"
            [ -n "$battery" ] && sys="${sys}${battery}${sep}"
            [ -n "$updates" ] && sys="${sys}${updates}${sep}"
            sys="${sys}${load} ${date}${dtime}"
            ;;
        W*)
            # bspwm's state
            twm=()
            IFS=':'
            # shellcheck disable=SC2086
            set -- ${line#?}
            active_mon=0
            layout=""
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    [mM]*)
                        [ "$num_mon" -lt 2 ] && shift && continue
                        case $item in
                            m*)
                                active_mon=0
                                ;;
                            M*)
                                active_mon=1
                                ;;
                        esac
                        ;;
                    [FoOuU]*)
                        desk=" ${name} "
                        case $item in
                            f*)
                                # free desktop
                                desk="%{F${COLOR_FREE_FG} B${COLOR_FREE_BG}} ${name} %{F- B-}"
                                ;;
                            F*)
                                # focused free desktop
                                desk="%{F- B- U${COLOR_FOCUSED_FREE_FG} +u} ${name} %{U- -u}"
                                ;;
                            o*)
                                # occupied desktop
                                desk="%{F${COLOR_OCCUPIED_FG} B${COLOR_OCCUPIED_BG}} ${name} %{F- B-}"
                                ;;
                            O*)
                                if [ "$active_mon" -eq 1 ]; then
                                    desk="%{F${COLOR_FOCUSED_OCCUPIED_FG} B${COLOR_FOCUSED_OCCUPIED_BG} U${COLOR_FOCUSED_OCCUPIED_FG} +u} ${name} %{F- U- -u}"
                                else
                                    desk="%{F${COLOR_OCCUPIED_FG} B${COLOR_OCCUPIED_BG} U${COLOR_OCCUPIED_FG} +u} ${name} %{F- U- -u}"
                                fi
                                ;;
                            u*)
                                # urgent desktop
                                desk="%{F${COLOR_OCCUPIED_FG} B${COLOR_OCCUPIED_BG}} ${name} %{F- B-}"
                                ;;
                            U*)
                                # focused urgent desktop
                                desk="%{F${COLOR_OCCUPIED_FG} B${COLOR_OCCUPIED_BG}} ${name} %{F- B-}"
                                ;;
                        esac
                        position="$(sed -n "/${name}$/ s/=.*$//p" "$HOME/.config/bspwm/desktops")"
                        twm[$position]="$desk"
                        ;;
                esac
                shift
            done
            wm=""
            for row in "${twm[@]}"; do
                wm="${wm}${row}"
            done
            wm="${wm}${layout}"
            ;;
    esac
    echo -e "%{l}${wm} ${title}%{c}${music}%{r}${sys}${offset}"
done
