#! /bin/sh

# shellcheck disable=SC1091
. bspwm_theme

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
    case $line in
        S*)
            sys="${line#?}"
            ;;
        T*)
            title="${line#?}"
            ;;
        W*)
            # bspwm's state
            twm=()
            IFS=':'
            # shellcheck disable=SC2086
            set -- ${line#?}
            active_mon=0
            layout=""
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    [mM]*)
                        [ "$num_mon" -lt 2 ] && shift && continue
                        case $item in
                            m*)
                                active_mon=0
                                ;;
                            M*)
                                active_mon=1
                                ;;
                        esac
                        ;;
                    [FoOuU]*)
                        desk=" ${name} "
                        case $item in
                            f*)
                                # free desktop
                                desk="%{F${COLOR_FREE_FG} B${COLOR_FREE_BG}} ${name} %{F- B-}"
                                ;;
                            F*)
                                # focused free desktop
                                desk="%{F- B- U${COLOR_FOCUSED_FREE_FG} +u} ${name} %{U- -u}"
                                ;;
                            o*)
                                # occupied desktop
                                desk="%{F${COLOR_OCCUPIED_FG} B${COLOR_OCCUPIED_BG}} ${name} %{F- B-}"
                                ;;
                            O*)
                                desk="%{F${COLOR_FOCUSED_OCCUPIED_FG} B- U${COLOR_FOCUSED_OCCUPIED_FG} +u} ${name} %{F- U- -u}"
                                ;;
                            u*)
                                # urgent desktop
                                desk="%{F${COLOR_OCCUPIED_FG} B${COLOR_OCCUPIED_BG}} ${name} %{F- B-}"
                                ;;
                            U*)
                                # focused urgent desktop
                                desk="%{F${COLOR_OCCUPIED_FG} B${COLOR_OCCUPIED_BG}} ${name} %{F- B-}"
                                ;;
                        esac
                        position="$(sed -n "/${name}$/ s/=.*$//p" "$HOME/.config/bspwm/desktops")"
                        twm[$position]="$desk"
                        ;;
                esac
                shift
            done
            wm=""
            for row in "${twm[@]}"; do
                wm="${wm}${row}"
            done
            wm="${wm}${layout}"
            ;;
    esac
    echo -e "%{l}${wm} ${title}%{r}${sys}"
done
