#! /bin/sh

export PATH=$PATH:$HOME/.config/bspwm/panel

if [ "$(pgrep -cx lemonbar)" -gt 1 ]; then
    echo "The panel is running. Stopping it"
    pkill -n "lemonbar"
    sleep 0.1
    while [[ $(prgep -c "lemonbar") != 0 ]]; do
        pkill -n -9 "lemonbar"
    done
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

# shellcheck disable=SC1091
. ./bspwm_theme

PANEL_FIFO=${PANEL_FIFO:-/tmp/panel-fifo}
[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

PANEL_WM_NAME=${PANEL_WM_NAME:-lemonbar}

# Reset the padding for all monitors
for mon in $(bspc query -M); do
    bspc config -m "$mon" top_padding 0
done

mon=$(bspc query -M -m primary)
# No primary monitor, take the first one
[ "$mon" ] || mon=$(bspc query -M -m "^1")


bspc config -m "$mon" top_padding "$PANEL_HEIGHT"
bspc subscribe report > "$PANEL_FIFO" &
#xtitle -s -t 80 -f "T%s" > "$PANEL_FIFO" &

pkill info.sh
info.sh

scroll() {
    while :; do
        zscroll -n -u -d 0.4 -l 40 -M "playerctl status" -m "Paused" -b "SM\uf04c" -s 0 -m "Playing" -b "SM\uf001 " -s 1 "$HOME/.config/bspwm/panel/np.sh" > "$PANEL_FIFO"
    done
}

tree_data=$(bspc query -T -m "$mon")
geometry=$(echo "$tree_data" | \
    jq -r '"\(.rectangle.width)x\(env.PANEL_HEIGHT)+\(.rectangle.x)"')


panel_bar < "$PANEL_FIFO" | lemonbar \
    -a 32 \
    -n "$PANEL_WM_NAME" \
    -g "$geometry" \
    -f "$PANEL_FONT" \
    -o 0 \
    -f "$PANEL_ICON_FONT" \
    -o -2 \
    -u 2 \
    -U "$COLOR_DEFAULT_BG" \
    -F "$COLOR_DEFAULT_FG" \
    -B "$COLOR_DEFAULT_BG" | sh >/dev/null &

wait
