#! /bin/sh

bspc config border_width        1
bspc config window_gap         12
bspc config focused_border_color '#d32f2f'

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config history_aware_focus true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc rule -a mpv state=floating
bspc rule -a Thunar state=floating
bspc rule -a keepassx state=floating
