#!/bin/bash

bspc config border_width              2
bspc config window_gap                12
bspc config focused_border_color      '#f99157'
bspc config normal_border_color       '#343d46'
bspc config active_border_color       '#343d46'

bspc config split_ratio               0.52
bspc config borderless_monocle        false
bspc config gapless_monocle           true
bspc config focus_by_distance         true
bspc config history_aware_focus       true
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config click_to_focus            true
bspc config pointer_follows_focus     false
bspc config pointer_follows_monitor   true

for line in $(< "$HOME/.config/bspwm/desktops"); do
    bspc monitor -a "$(cut -d'=' -f2 <<< "$line")"
done

bspc rule -a mpv state=floating center=on
bspc rule -a Thunar state=floating center=on
bspc rule -a keepassx state=floating
bspc rule -a Pcmanfm state=floating center=on

$HOME/.config/bspwm/reset-status.sh
